### ISSUE TITLE
Only output the styles that are actually used

### ISSUE THREAD

**Issue by nigelmegitt** [IRT-Open-Source/scf#10]
The current STLXML2EBU-TT stylesheet always outputs the whole set of styles for all the different foreground and background colour combinations even if only a subset of those styles are used. Those are then copied across by EBU-TT2EBU-TT-D and are therefore preserved. It would be a good improvement to insert only those styles into the EBU-TT that are actually used.

**Comment by tairt** [comment]
This is indeed an issue we noted and we implemented an XSLT some time ago that solve this issue but it has not been pushed and merged yet. It will be there in the next release.

**Comment by nigelmegitt** [comment]
Great, I look forward to that. If you could make it available sooner that would be extremely useful.

**Comment by tairt** [comment]
The module is now published https://github.com/IRT-Open-Source/scf/tree/master/modules/TT-Helper/TT-Filter-Styles-No-References

**Comment by nigelmegitt** [comment]
Thanks - works great!
