### ISSUE TITLE
Calculate offset based on `ebuttm:documentStartOfProgramme`

### ISSUE THREAD

**Issue by nigelmegitt** [IRT-Open-Source/scf#12]
When converting from `timebase="smpte"` to `timebase="media"` it would be ideal to offer a setting (or indeed make it the default) to use the value of `TCP` or equivalently `ebuttm:documentStartOfProgramme` as the offset and discard any content that falls before that timecode.

For example, an EBU-TT document is created from an STL document and has:
- `timebase="smpte"`,
- a 'subtitle zero' at 00:00:00,
- a `ebuttm:documentStartOfProgramme="10:00:00"` and
- most of the content falls after 10:00:00. 

This should generate an EBU-TT-D document with:
- `timebase="media"`,
- no subtitle zero
- the content is offset backwards by 10:00:00: an element whose `begin="10:00:00"` in the EBU-TT should have `begin="00:00:00"` in the EBU-TT-D.

**Comment by tairt** [comment]
Yes this makes sense and was also raised by other parties who use the script to convert "broadcast" subtitles to "internet" subtitles.

The solution may as simple as to have a new parameter (e.g. offsetTcp or offsetSop for offset Start of program) and to set the value of the "offsetInFrames" parameter accordingly. The processing should stop if offsetTcp AND offsetInSeconds and offsetInFrames have been specified.

**Comment by spoeschel** [comment]
Sorry for the quite long delay!

We will add respective parameters to `STLXML2EBU-TT` and `EBU-TT2EBU-TT-D` that will use the `TCP`/`ebuttm:documentStartOfProgramme` values, to adjust all timecodes accordingly.

**Comment by spoeschel** [comment]
The example also affects the subtitle zero, which is already covered by #13. Therefore we will address that specific aspect there (distinct from the resolution of this issue here).

**Comment by spoeschel** [comment]
Fixed in version 1.0.
