### ISSUE TITLE
STL2STLXML: Translation of "$" character is missing for ISO6937/2

### ISSUE THREAD

**Issue by spoeschel** [IRT-Open-Source/scf#19]
The Dollar sign "$" is not translated in the Text Field element if an STL file uses as encoding Character Code Table "00" (from ISO 6937/2-1983 for the TTI blocks). No other code point is generated at all.

**Comment by tairt** [comment]
Ging ja fix : ) Danke!

Am 20.04.2016 um 10:35 schrieb Stefan Pöschel:
>
> The Dollar sign "$" is not translated in the Text Field element if an 
> STL file uses as encoding Character Code Table "00" (from ISO 
> 6937/2-1983 for the TTI blocks). No other code point is generated at all.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/IRT-Open-Source/scf/issues/19>
>


-- 
------------------------------------------------
Andreas Tai
Production Systems Television IRT - Institut fuer Rundfunktechnik GmbH
R&D Institute of ARD, ZDF, DRadio, ORF and SRG/SSR
Floriansmuehlstrasse 60, D-80939 Munich, Germany

Phone: +49 89 32399-389 | Fax: +49 89 32399-200
http: www.irt.de | Email: tai@irt.de
------------------------------------------------

registration court&  managing director:
Munich Commercial, RegNo. B 5191
Dr. Klaus Illgner-Fehns
------------------------------------------------
