### ISSUE TITLE
STLXML2EBU-TT: handling of content out of boxing

### ISSUE THREAD

**Issue by spoeschel** [IRT-Open-Source/scf#26]
When a subtitle's TF contains content that is not enclosed by `StartBox`/`EndBox` element pairs, currently spaces (in the form of `space` elements) are discarded - but any text is copied. E.g. in case of `This is a test.` in STL (without enclosing boxing), this results in `Thisisatest.` in EBU-TT.

For consistency space/text content outside of boxing should be treat equally i.e. text should be discarded as well in that case.

An alternative way is to discard neither spaces nor text in case the TF does not use boxing at all (which is sometimes seen in STL files).

**Comment by braincoded** [comment]
I've experienced this issue with EBU STL files containing open subtitles.
Whether a file contains closed captions or open captions isn't evaluated by SCF and can thus lead to the result described above.

**Comment by spoeschel** [comment]
This will be fixed and adhere to the above described "alternative way" i.e. to discard only text which is outside of (present) boxing.
