### ISSUE TITLE
STL2STLXML: Empty subtitles get lost

### ISSUE THREAD

**Issue by braincoded** [IRT-Open-Source/scf#29]
In EBU STL files containing teletext closed captions often empty subtitles occur on purpose.

a) Background
If there are longer periods without dialog or noises to be described editors place an empty subtitle to signal all receivers of the viewers who might switched to a channel in the meantime that closed captions are transmitted. Otherwise the search for teletext page 888, 777, 150 etc. can run much longer.

b) Problem introduced by SCF
Omitting empty subtitles leads to two main problems:
- Round tripping issues due to differences in total no. of subtitles, TC of first/last subtitle cross referenced in metadata workflows, etc.
- Communication issues between editors creating/checking a file due to the different numbering in the source file and the converted/round tripped one.

c) Expected behavior
SCF should respect every single subtitle no matter whether it is empty or not.

**Comment by spoeschel** [comment]
This aspect will be addressed soon i.e. subtitles without text (TF only contains `0x8F`) will be converted to STLXML as well.
