### ISSUE TITLE
STLXML2EBU-TT: set documentCreationDate/documentRevisionDate

### ISSUE THREAD

**Issue by spoeschel** [IRT-Open-Source/scf#40]
The two EBU-TT fields `ebuttm:documentCreationDate` and `ebuttm:documentRevisionDate` shall be set/initialized with the current date.

**Comment by braincoded** [comment]
Shouldn't the two EBU-TT fields inherit the corresponding values from the EBU STL file instead of being set/overwritten with the current date? As long as the content of the original file isn't altered this seems to make more sens to me and it would be essential for round tripping reasons. Am I missing something?

**Comment by spoeschel** [comment]
The respective fields from EBU STL are already covered by #34; they are stored in separate metadata fields.

**Comment by braincoded** [comment]
THX!

**Comment by tairt** [comment]
Just for completeness: `ebuttm:documentCreationDate` and `ebuttm:documentRevisionDate` in EBU-TT Part 1 version 1.0 were indeed intended to be the corresponding fields for STL Creation Date and STL Revision Number. But there was the conflict that the fields in the description were meant to be the creation data and revision number of the EBU-TT XML document, so the STL metatadata would be overwritten.

The workaround that was found in EBU-TT Part 2 version 0.9 to map the STL GSI fields to the `ebuttExt:` namespace. As currently SCF is based on EBU-TT Part 1 version 1.0 and EBU-TT Part 2 version 0.9 we follow this strategy.

When SCF will be based on the latest specs (so a later version of EBU-TT Part 1 and the 1.0 version of EBU-TT Part 2) this will again be changed. EBU-TT Part 1 version 1.1 defines `ebuttm:stlCreationDate` and `ebuttm:stlRevisionNumber` and SCF will use these new fields. The STL Mapping guide (EBU-TT Part 2) is not published yet as 1.0 but is expected to be published this year.
