### ISSUE TITLE
STL2STLXML: add option to discard UDA field + User Data TTI blocks

### ISSUE THREAD

**Issue by basicmaster** [IRT-Open-Source/scf#44]
There should be an option to discard the user data that can be contained within a TTI block.

**Comment by spoeschel** [comment]
As this may already affect the workflow `STL -> STLXML -> STL`, it makes more sense to add this option to `STL2STLXML`.

**Comment by spoeschel** [comment]
And to also discard the content of the GSI block's UDA field.

**Comment by braincoded** [comment]
Please handle the two cases separately, i. e. one should be able to disable them individually. 
While a) user data within the TTI block can cause problems in some subtitle editors, when user data in the TTI block after a STL -> STLXML -> manipulation -> STL conversion is given priority over the regular TTI data and thus one should be able to discard it,
b) the GSI/UDA should still be usable and not discarded simultaneously.
Thanks!

**Comment by spoeschel** [comment]
We will indeed handle the two cases separately, for the reason you mentioned, to be flexible in discarding/clearing this user data.
