### ISSUE TITLE
STL2STLXML/STLXML2EBU-TT: don't convert trailing spaces in UDA field

### ISSUE THREAD

**Issue by spoeschel** [IRT-Open-Source/scf#45]
If the UDA field not completely consists of meaningful data, the remaining bytes are filled up with spaces. According to EBU Tech 3360 (ch. 3.10 in v0.9) such trailing spaces should not be converted.

**Comment by tairt** [comment]
It maybe important to note that Tech3360 defines the mapping from STL to EBU-TT Part and not for the STLXML representation. So this is not a bug but an enhancement that eases further processing (e.g. when converting to EBU-TT Part 1).
