### ISSUE TITLE
Change requirement for StartBox and EndBox mapping

### ISSUE THREAD

**Issue by pthopesch** [IRT-Open-Source/scf#48]
Refers to module: STLXML2EBU-TT

Currently the processing is not consistent, when handling teletext control codes (CC) in the 'TF' (text field of the TTI block). According to EBU Tech 3360, StartBox/EndBox should close the current span and open a new one. Same for color CCs (AplphaBlack, AlphaGreen, ...). For StadtBox/EndBox the requirements reflect exactly that. However, for color CCs the requirements state that a new span is created only when the CC changes the subtitle style (foreground or background color). That means there will be no two consecutive spans with the same style. 

For StartBox/EndBox the processing should be the same as for color CCs.

For most real world  STLXML files this will not be an issue since every line uses only one box.

**Comment by tairt** [comment]
I think that this should not be changed for the time being. Control codes are not meant to open anything new other then to apply color. StartBox/EndBox map quite well to other a content container like a span.

**Comment by pthopesch** [comment]
OK.
