### ISSUE TITLE
STLXML - invalid value for VP = "0"

### ISSUE THREAD

**Issue by kbachmeier** [IRT-Open-Source/scf#69]
We use STL2STLXML and STLXML2EBU-TT to convert our STL-files to EBU-TT. Now we had an error with the STLXML2EBU-TT, caused by an invalid value for VP:
_"The only possible values of VP are decimal numbers between 1 and 23"_
Our STLXML contains the value "0" at the Node /StlXml/BODY[1]/TTICONTAINER[1]/TTI[1]/VP[1]

So the question is: do we have an invald STL file or are there problems within the STL2STLXML?

[VP-Error.zip](https://github.com/IRT-Open-Source/scf/files/4699902/VP-Error.zip)

**Comment by spoeschel** [comment]
In this case the input file clearly violates the EBU STL spec: The STL file indicates "Level-1 Teletext" subtitles in the GSI header (`DSC` field set to value `1`). As a consequence the vertical position (VP) field must always be in the range 1 to 23 (refering to the available Teletext line numbers) then, according to the EBU STL spec. So the value 0 is forbidden here.

**Comment by kbachmeier** [comment]
Ok, thank you! I will return this info to the colleagues from whom we got the file.

**Comment by tairt** [comment]
@kbachmeier See also [EBU Tech 3264](https://tech.ebu.ch/docs/tech/tech3264.pdf) page 12 (bottom)

**Comment by kbachmeier** [comment]
ok, good to know

**Comment by tairt** [comment]
As the root of the problem seems to be found I will close the ticket for now. @kbachmeier if you have additional questions or comments on this issue, feel free to re-open this ticket.
