### ISSUE TITLE
EBU-TT2STLXML: consider UDA field

### ISSUE THREAD

**Issue by spoeschel** [IRT-Open-Source/scf#71]
As STLXML supports/requires the `UDA` field since 41efaa5a5b64aa2b606c2c79cb95e691984dbb8e, it has to be considered in this conversion module.

**Comment by jayotirana** [comment]
Hello @spoeschel , 
Is there any plan to release it soon.
Thanks

**Comment by tairt** [comment]
Hi @jayotirana! Thanks for asking! We are currently discussing a good solution for the issue and hope to provide it soon. We will come back with a more concrete proposal. Thanks for your patience : )

**Comment by spoeschel** [comment]
@jayotirana We will release a new version with this fix in the next days/weeks, in any case before end of July.

**Comment by jayotirana** [comment]
Thanks for the update @spoeschel.
