### ISSUE TITLE
Provide Docker container on Dockerhub

### ISSUE THREAD

**Issue by ut-worker** [IRT-Open-Source/scf#72]
Hi there,

Thank you for your amazing work on SCF!

We are using SCF here at SWR and worked at an automatic build of the Docker container. We are using GitLab-CI for that. The code is hosted here: https://gitlab.com/broadcast-tools/scf

Currently the latest SCF Version (1.8.1) ist available as a Docker container here: registry.gitlab.com/broadcast-tools/scf

Is there any plan to automatically provide your Docker container ? (on DockerHub for example). If not, you could reference our Docker container in your Readme.

**Comment by spoeschel** [comment]
Hi,

thanks for the kudos, and the infos and the suggestion!

So far it was no point on our TODO list to provide a prebuilt Docker image, but it absolutely makes sense to do so. So I had a look into this and configured a repo at Docker Hub: https://hub.docker.com/r/irtopensource/scf_service

Besides the `latest` tag, there will also be images that refer to a published version (tag) once a new version is pushed.

Would this fit your needs?

**Comment by spoeschel** [comment]
Due to the recent developments regarding IRT's future, we unfortunately won't be able to look after such image in the future. Therefore I removed the image from Docker hub.

**Comment by gizmo84** [comment]
Schade! Thanks you for looking at this and again for your amazing work!

**Comment by spoeschel** [comment]
Thanks for your words!
