### ISSUE TITLE
STL2STLXML: Translation of "~" character is missing for ISO6937/2

### ISSUE THREAD

**Issue by tairt** [IRT-Open-Source/scf#9]
The character for tilde "~" is not translated in the textfield element if a STL file uses as encoding character code table "00" (from ISO 6937/2-198 for the TTI blocks). No other code point is generated at all.

**Comment by yanncoupin** [comment]
Tilde is 007E in unicode and is in the `identical` set that should be passed as-is in the output. You modified the range during the fork and it's missing.

`identical = set(range(0x21, 0x7e))`

should be

`identical = set(range(0x21, 0x7f))`

**Comment by tairt** [comment]
Hi Yann,

Your are absolutely right. It is the code range and I fixed it already. I push the fix with the next release.

Andreas
